# Generated by Django 6.0.2 on 2026-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_discord_access_token_profile_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(choices=[('#7b2ff7', 'Mitsu Purple'), ('#ff6b6b', 'Ruby Red'), ('#4ecdc4', 'Mint Green'), ('#feca57', 'Sunset Orange'), ('#54a0ff', 'Ocean Blue'), ('#ff9ff3', 'Sakura Pink')], default='#7b2ff7', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='dark', max_length=10),
        ),
    ]
