# Generated by Django 6.0.2 on 2026-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_accent_color_profile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimeentry',
            name='anime_id',
            field=models.IntegerField(db_index=True, help_text='MAL Anime ID'),
        ),
        migrations.AlterField(
            model_name='useranimeentry',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('plan_to_watch', 'Plan to Watch'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], db_index=True, default='plan_to_watch', max_length=20),
        ),
    ]
