# Generated by Django 6.0.2 on 2026-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
