# Generated by Django 6.0.2 on 2026-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text_hash', models.CharField(db_index=True, max_length=32)),
                ('source_lang', models.CharField(default='en', max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text_hash', 'target_lang'], name='app_transla_source__0bde7d_idx')],
                'unique_together': {('source_text_hash', 'target_lang')},
            },
        ),
    ]
