# Generated by Django 6.0.2 on 2026-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('new_review', 'New Review'), ('review_like', 'Review Like')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='anime_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='anime_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
