# Generated by Django 6.0.2 on 2026-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_activity_activity_type_alter_activity_anime_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
