# Generated by Django 6.0.2 on 2026-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_is_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review_like', 'Review Like'), ('review_comment', 'Review Comment'), ('new_follower', 'New Follower'), ('system', 'System Message')], max_length=20),
        ),
    ]
