# Generated by Django 6.0.2 on 2026-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review_like', 'Review Like'), ('review_comment', 'Review Comment'), ('new_follower', 'New Follower'), ('system', 'System Message'), ('badge_earned', 'Badge Earned')], max_length=20),
        ),
    ]
