# Generated by Django 6.0.2 on 2026-04-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_animemetadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('anime_id', models.IntegerField(blank=True, null=True)),
                ('video_url', models.URLField(max_length=1000)),
                ('status', models.CharField(default='paused', max_length=20)),
                ('current_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
